### ISSUE TITLE
Demo offline?

### ISSUE THREAD

**Issue by pwFoo** [hvxahv/hvxahv#104]
Hi,

is there a demo site to see how it works / feels to use it?
The link doesn't work.

**Comment by disism** [comment]
> Hi,
> 
> is there a demo site to see how it works / feels to use it? The link doesn't work.

Hello. Thank you for your attention.
The current system is just a simple exploration, the program code is also very messy, and the demo is not fully implemented. This project will implement a completely decentralized social system, using activitypub as the account system, matrix as the chat system, and ipfs as the user's cloud drive. And similar to the telegram channel function, the private key will be stored on the user's client. When the multi-end login exchanges the key, the key is exchanged in the form of end-to-end encryption, which has nothing to do with the server.
The current system is in the design and implementation stage, so there are still a lot of things to do. I am working hard to achieve it. You are welcome to pay attention to and participate in the project.
Developer Telegram: https://t.me/hvturingga
Email: x@disism.com
